/**
 * Mock product data for frontend development.
 * Will be replaced by Supabase queries in the backend phase.
 */
import type { Product } from "@/lib/products";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Cashmere-Schal in Sandbeige",
    slug: "cashmere-schal-sandbeige",
    kategorie: "schals",
    material: "cashmere",
    preis: 129,
    kurzbeschreibung:
      "Federleichter Cashmere-Schal in warmem Sandbeige. Handgewebt in der Mongolei aus feinster Innenmongolei-Cashmere.",
    hauptbild: "/images/placeholder-product.jpg",
    auf_lager: true,
    neu: true,
    erstellt_am: "2026-02-15T10:00:00Z",
  },
  {
    id: "2",
    name: "Yak-Wolldecke Naturbraun",
    slug: "yak-wolldecke-naturbraun",
    kategorie: "decken",
    material: "yak",
    preis: 249,
    kurzbeschreibung:
      "Kuschelig warme Yak-Wolldecke in natürlichem Braun. Perfekt für kalte Abende auf dem Sofa.",
    hauptbild: "/images/placeholder-product.jpg",
    auf_lager: true,
    neu: true,
    erstellt_am: "2026-02-14T10:00:00Z",
  },
  {
    id: "3",
    name: "Schafwoll-Mütze Steingrau",
    slug: "schafwoll-muetze-steingrau",
    kategorie: "muetzen",
    material: "schafwolle",
    preis: 39,
    kurzbeschreibung:
      "Warme Mütze aus mongolischer Schafwolle in dezentem Steingrau. Handgestrickt, weich und langlebig.",
    hauptbild: "/images/placeholder-product.jpg",
    auf_lager: true,
    neu: false,
    erstellt_am: "2026-02-10T10:00:00Z",
  },
  {
    id: "4",
    name: "Cashmere-Schal Himmelblau",
    slug: "cashmere-schal-himmelblau",
    kategorie: "schals",
    material: "cashmere",
    preis: 139,
    kurzbeschreibung:
      "Eleganter Cashmere-Schal in zartem Himmelblau. Ein Hauch von Luxus für jeden Tag.",
    hauptbild: "/images/placeholder-product.jpg",
    auf_lager: true,
    neu: false,
    erstellt_am: "2026-02-08T10:00:00Z",
  },
  {
    id: "5",
    name: "Kamelwoll-Plaid Wüstengold",
    slug: "kamelwoll-plaid-wuestengold",
    kategorie: "decken",
    material: "kamelwolle",
    preis: 189,
    kurzbeschreibung:
      "Wärmende Kamelwoll-Decke in warmem Goldton. Die feine Faser der Baktrischen Kamele ist besonders isolierend.",
    hauptbild: "/images/placeholder-product.jpg",
    auf_lager: true,
    neu: false,
    erstellt_am: "2026-02-05T10:00:00Z",
  },
  {
    id: "6",
    name: "Yak-Schal Mitternachtsblau",
    slug: "yak-schal-mitternachtsblau",
    kategorie: "schals",
    material: "yak",
    preis: 89,
    kurzbeschreibung:
      "Weicher Yak-Woll-Schal in tiefem Mitternachtsblau. Wärmer als Cashmere, robust und nachhaltig.",
    hauptbild: "/images/placeholder-product.jpg",
    auf_lager: false,
    neu: false,
    erstellt_am: "2026-01-28T10:00:00Z",
  },
  {
    id: "7",
    name: "Cashmere-Handschuhe Cremeweiss",
    slug: "cashmere-handschuhe-cremeweiss",
    kategorie: "accessoires",
    material: "cashmere",
    preis: 69,
    kurzbeschreibung:
      "Zarte Cashmere-Handschuhe in Cremeweiß. Hält die Hände warm ohne zu beschweren.",
    hauptbild: "/images/placeholder-product.jpg",
    auf_lager: true,
    neu: true,
    erstellt_am: "2026-02-18T10:00:00Z",
  },
  {
    id: "8",
    name: "Schafwoll-Schal Naturweiss",
    slug: "schafwoll-schal-naturweiss",
    kategorie: "schals",
    material: "schafwolle",
    preis: 59,
    kurzbeschreibung:
      "Klassischer Schal aus feiner mongolischer Schafwolle. Naturbelassen und wunderbar weich.",
    hauptbild: "/images/placeholder-product.jpg",
    auf_lager: true,
    neu: false,
    erstellt_am: "2026-01-20T10:00:00Z",
  },
  {
    id: "9",
    name: "Yak-Mütze Anthrazit",
    slug: "yak-muetze-anthrazit",
    kategorie: "muetzen",
    material: "yak",
    preis: 49,
    kurzbeschreibung:
      "Robuste Mütze aus Yak-Wolle in elegantem Anthrazit. Hält auch bei minus 20 Grad warm.",
    hauptbild: "/images/placeholder-product.jpg",
    auf_lager: true,
    neu: false,
    erstellt_am: "2026-01-15T10:00:00Z",
  },
  {
    id: "10",
    name: "Kamelwoll-Schal Terrakotta",
    slug: "kamelwoll-schal-terrakotta",
    kategorie: "schals",
    material: "kamelwolle",
    preis: 99,
    kurzbeschreibung:
      "Edler Schal aus Kamelwolle in warmer Terrakotta-Farbe. Die natürliche Faser reguliert die Temperatur.",
    hauptbild: "/images/placeholder-product.jpg",
    auf_lager: true,
    neu: false,
    erstellt_am: "2026-01-10T10:00:00Z",
  },
  {
    id: "11",
    name: "Cashmere-Decke Rosé",
    slug: "cashmere-decke-rose",
    kategorie: "decken",
    material: "cashmere",
    preis: 349,
    kurzbeschreibung:
      "Luxuriöse Cashmere-Decke in zartem Rosé. Das perfekte Geschenk für besondere Anlässe.",
    hauptbild: "/images/placeholder-product.jpg",
    auf_lager: false,
    neu: false,
    erstellt_am: "2026-01-05T10:00:00Z",
  },
  {
    id: "12",
    name: "Kamelwoll-Stirnband Cognac",
    slug: "kamelwoll-stirnband-cognac",
    kategorie: "accessoires",
    material: "kamelwolle",
    preis: 35,
    kurzbeschreibung:
      "Praktisches Stirnband aus Kamelwolle in warmem Cognac-Ton. Ideal für Übergangsmonate.",
    hauptbild: "/images/placeholder-product.jpg",
    auf_lager: true,
    neu: true,
    erstellt_am: "2026-02-20T10:00:00Z",
  },
];
